/*
OWASP Dependency-Track

REST API of OWASP Dependency-Track

API version: 4.13.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Publisher type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Publisher{}

// Publisher struct for Publisher
type Publisher struct {
	Uuid string `json:"uuid"`
}

type _Publisher Publisher

// NewPublisher instantiates a new Publisher object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublisher(uuid string) *Publisher {
	this := Publisher{}
	this.Uuid = uuid
	return &this
}

// NewPublisherWithDefaults instantiates a new Publisher object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublisherWithDefaults() *Publisher {
	this := Publisher{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *Publisher) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *Publisher) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *Publisher) SetUuid(v string) {
	o.Uuid = v
}

func (o Publisher) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Publisher) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	return toSerialize, nil
}

func (o *Publisher) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublisher := _Publisher{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPublisher)

	if err != nil {
		return err
	}

	*o = Publisher(varPublisher)

	return err
}

type NullablePublisher struct {
	value *Publisher
	isSet bool
}

func (v NullablePublisher) Get() *Publisher {
	return v.value
}

func (v *NullablePublisher) Set(val *Publisher) {
	v.value = val
	v.isSet = true
}

func (v NullablePublisher) IsSet() bool {
	return v.isSet
}

func (v *NullablePublisher) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublisher(val *Publisher) *NullablePublisher {
	return &NullablePublisher{value: val, isSet: true}
}

func (v NullablePublisher) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublisher) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


