/*
OWASP Dependency-Track

REST API of OWASP Dependency-Track

API version: 4.13.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DependencyMetrics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DependencyMetrics{}

// DependencyMetrics struct for DependencyMetrics
type DependencyMetrics struct {
	Critical int32 `json:"critical"`
	High int32 `json:"high"`
	Medium int32 `json:"medium"`
	Low int32 `json:"low"`
	Unassigned *int32 `json:"unassigned,omitempty"`
	Vulnerabilities *int64 `json:"vulnerabilities,omitempty"`
	Suppressed *int32 `json:"suppressed,omitempty"`
	FindingsTotal *int32 `json:"findingsTotal,omitempty"`
	FindingsAudited *int32 `json:"findingsAudited,omitempty"`
	FindingsUnaudited *int32 `json:"findingsUnaudited,omitempty"`
	InheritedRiskScore *float64 `json:"inheritedRiskScore,omitempty"`
	PolicyViolationsFail *int32 `json:"policyViolationsFail,omitempty"`
	PolicyViolationsWarn *int32 `json:"policyViolationsWarn,omitempty"`
	PolicyViolationsInfo *int32 `json:"policyViolationsInfo,omitempty"`
	PolicyViolationsTotal *int32 `json:"policyViolationsTotal,omitempty"`
	PolicyViolationsAudited *int32 `json:"policyViolationsAudited,omitempty"`
	PolicyViolationsUnaudited *int32 `json:"policyViolationsUnaudited,omitempty"`
	PolicyViolationsSecurityTotal *int32 `json:"policyViolationsSecurityTotal,omitempty"`
	PolicyViolationsSecurityAudited *int32 `json:"policyViolationsSecurityAudited,omitempty"`
	PolicyViolationsSecurityUnaudited *int32 `json:"policyViolationsSecurityUnaudited,omitempty"`
	PolicyViolationsLicenseTotal *int32 `json:"policyViolationsLicenseTotal,omitempty"`
	PolicyViolationsLicenseAudited *int32 `json:"policyViolationsLicenseAudited,omitempty"`
	PolicyViolationsLicenseUnaudited *int32 `json:"policyViolationsLicenseUnaudited,omitempty"`
	PolicyViolationsOperationalTotal *int32 `json:"policyViolationsOperationalTotal,omitempty"`
	PolicyViolationsOperationalAudited *int32 `json:"policyViolationsOperationalAudited,omitempty"`
	PolicyViolationsOperationalUnaudited *int32 `json:"policyViolationsOperationalUnaudited,omitempty"`
	// UNIX epoch timestamp in milliseconds
	FirstOccurrence int64 `json:"firstOccurrence"`
	// UNIX epoch timestamp in milliseconds
	LastOccurrence int64 `json:"lastOccurrence"`
}

type _DependencyMetrics DependencyMetrics

// NewDependencyMetrics instantiates a new DependencyMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDependencyMetrics(critical int32, high int32, medium int32, low int32, firstOccurrence int64, lastOccurrence int64) *DependencyMetrics {
	this := DependencyMetrics{}
	this.Critical = critical
	this.High = high
	this.Medium = medium
	this.Low = low
	this.FirstOccurrence = firstOccurrence
	this.LastOccurrence = lastOccurrence
	return &this
}

// NewDependencyMetricsWithDefaults instantiates a new DependencyMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDependencyMetricsWithDefaults() *DependencyMetrics {
	this := DependencyMetrics{}
	return &this
}

// GetCritical returns the Critical field value
func (o *DependencyMetrics) GetCritical() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Critical
}

// GetCriticalOk returns a tuple with the Critical field value
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetCriticalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Critical, true
}

// SetCritical sets field value
func (o *DependencyMetrics) SetCritical(v int32) {
	o.Critical = v
}

// GetHigh returns the High field value
func (o *DependencyMetrics) GetHigh() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.High
}

// GetHighOk returns a tuple with the High field value
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetHighOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.High, true
}

// SetHigh sets field value
func (o *DependencyMetrics) SetHigh(v int32) {
	o.High = v
}

// GetMedium returns the Medium field value
func (o *DependencyMetrics) GetMedium() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Medium
}

// GetMediumOk returns a tuple with the Medium field value
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetMediumOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Medium, true
}

// SetMedium sets field value
func (o *DependencyMetrics) SetMedium(v int32) {
	o.Medium = v
}

// GetLow returns the Low field value
func (o *DependencyMetrics) GetLow() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Low
}

// GetLowOk returns a tuple with the Low field value
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetLowOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Low, true
}

// SetLow sets field value
func (o *DependencyMetrics) SetLow(v int32) {
	o.Low = v
}

// GetUnassigned returns the Unassigned field value if set, zero value otherwise.
func (o *DependencyMetrics) GetUnassigned() int32 {
	if o == nil || IsNil(o.Unassigned) {
		var ret int32
		return ret
	}
	return *o.Unassigned
}

// GetUnassignedOk returns a tuple with the Unassigned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetUnassignedOk() (*int32, bool) {
	if o == nil || IsNil(o.Unassigned) {
		return nil, false
	}
	return o.Unassigned, true
}

// HasUnassigned returns a boolean if a field has been set.
func (o *DependencyMetrics) HasUnassigned() bool {
	if o != nil && !IsNil(o.Unassigned) {
		return true
	}

	return false
}

// SetUnassigned gets a reference to the given int32 and assigns it to the Unassigned field.
func (o *DependencyMetrics) SetUnassigned(v int32) {
	o.Unassigned = &v
}

// GetVulnerabilities returns the Vulnerabilities field value if set, zero value otherwise.
func (o *DependencyMetrics) GetVulnerabilities() int64 {
	if o == nil || IsNil(o.Vulnerabilities) {
		var ret int64
		return ret
	}
	return *o.Vulnerabilities
}

// GetVulnerabilitiesOk returns a tuple with the Vulnerabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetVulnerabilitiesOk() (*int64, bool) {
	if o == nil || IsNil(o.Vulnerabilities) {
		return nil, false
	}
	return o.Vulnerabilities, true
}

// HasVulnerabilities returns a boolean if a field has been set.
func (o *DependencyMetrics) HasVulnerabilities() bool {
	if o != nil && !IsNil(o.Vulnerabilities) {
		return true
	}

	return false
}

// SetVulnerabilities gets a reference to the given int64 and assigns it to the Vulnerabilities field.
func (o *DependencyMetrics) SetVulnerabilities(v int64) {
	o.Vulnerabilities = &v
}

// GetSuppressed returns the Suppressed field value if set, zero value otherwise.
func (o *DependencyMetrics) GetSuppressed() int32 {
	if o == nil || IsNil(o.Suppressed) {
		var ret int32
		return ret
	}
	return *o.Suppressed
}

// GetSuppressedOk returns a tuple with the Suppressed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetSuppressedOk() (*int32, bool) {
	if o == nil || IsNil(o.Suppressed) {
		return nil, false
	}
	return o.Suppressed, true
}

// HasSuppressed returns a boolean if a field has been set.
func (o *DependencyMetrics) HasSuppressed() bool {
	if o != nil && !IsNil(o.Suppressed) {
		return true
	}

	return false
}

// SetSuppressed gets a reference to the given int32 and assigns it to the Suppressed field.
func (o *DependencyMetrics) SetSuppressed(v int32) {
	o.Suppressed = &v
}

// GetFindingsTotal returns the FindingsTotal field value if set, zero value otherwise.
func (o *DependencyMetrics) GetFindingsTotal() int32 {
	if o == nil || IsNil(o.FindingsTotal) {
		var ret int32
		return ret
	}
	return *o.FindingsTotal
}

// GetFindingsTotalOk returns a tuple with the FindingsTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetFindingsTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.FindingsTotal) {
		return nil, false
	}
	return o.FindingsTotal, true
}

// HasFindingsTotal returns a boolean if a field has been set.
func (o *DependencyMetrics) HasFindingsTotal() bool {
	if o != nil && !IsNil(o.FindingsTotal) {
		return true
	}

	return false
}

// SetFindingsTotal gets a reference to the given int32 and assigns it to the FindingsTotal field.
func (o *DependencyMetrics) SetFindingsTotal(v int32) {
	o.FindingsTotal = &v
}

// GetFindingsAudited returns the FindingsAudited field value if set, zero value otherwise.
func (o *DependencyMetrics) GetFindingsAudited() int32 {
	if o == nil || IsNil(o.FindingsAudited) {
		var ret int32
		return ret
	}
	return *o.FindingsAudited
}

// GetFindingsAuditedOk returns a tuple with the FindingsAudited field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetFindingsAuditedOk() (*int32, bool) {
	if o == nil || IsNil(o.FindingsAudited) {
		return nil, false
	}
	return o.FindingsAudited, true
}

// HasFindingsAudited returns a boolean if a field has been set.
func (o *DependencyMetrics) HasFindingsAudited() bool {
	if o != nil && !IsNil(o.FindingsAudited) {
		return true
	}

	return false
}

// SetFindingsAudited gets a reference to the given int32 and assigns it to the FindingsAudited field.
func (o *DependencyMetrics) SetFindingsAudited(v int32) {
	o.FindingsAudited = &v
}

// GetFindingsUnaudited returns the FindingsUnaudited field value if set, zero value otherwise.
func (o *DependencyMetrics) GetFindingsUnaudited() int32 {
	if o == nil || IsNil(o.FindingsUnaudited) {
		var ret int32
		return ret
	}
	return *o.FindingsUnaudited
}

// GetFindingsUnauditedOk returns a tuple with the FindingsUnaudited field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetFindingsUnauditedOk() (*int32, bool) {
	if o == nil || IsNil(o.FindingsUnaudited) {
		return nil, false
	}
	return o.FindingsUnaudited, true
}

// HasFindingsUnaudited returns a boolean if a field has been set.
func (o *DependencyMetrics) HasFindingsUnaudited() bool {
	if o != nil && !IsNil(o.FindingsUnaudited) {
		return true
	}

	return false
}

// SetFindingsUnaudited gets a reference to the given int32 and assigns it to the FindingsUnaudited field.
func (o *DependencyMetrics) SetFindingsUnaudited(v int32) {
	o.FindingsUnaudited = &v
}

// GetInheritedRiskScore returns the InheritedRiskScore field value if set, zero value otherwise.
func (o *DependencyMetrics) GetInheritedRiskScore() float64 {
	if o == nil || IsNil(o.InheritedRiskScore) {
		var ret float64
		return ret
	}
	return *o.InheritedRiskScore
}

// GetInheritedRiskScoreOk returns a tuple with the InheritedRiskScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetInheritedRiskScoreOk() (*float64, bool) {
	if o == nil || IsNil(o.InheritedRiskScore) {
		return nil, false
	}
	return o.InheritedRiskScore, true
}

// HasInheritedRiskScore returns a boolean if a field has been set.
func (o *DependencyMetrics) HasInheritedRiskScore() bool {
	if o != nil && !IsNil(o.InheritedRiskScore) {
		return true
	}

	return false
}

// SetInheritedRiskScore gets a reference to the given float64 and assigns it to the InheritedRiskScore field.
func (o *DependencyMetrics) SetInheritedRiskScore(v float64) {
	o.InheritedRiskScore = &v
}

// GetPolicyViolationsFail returns the PolicyViolationsFail field value if set, zero value otherwise.
func (o *DependencyMetrics) GetPolicyViolationsFail() int32 {
	if o == nil || IsNil(o.PolicyViolationsFail) {
		var ret int32
		return ret
	}
	return *o.PolicyViolationsFail
}

// GetPolicyViolationsFailOk returns a tuple with the PolicyViolationsFail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetPolicyViolationsFailOk() (*int32, bool) {
	if o == nil || IsNil(o.PolicyViolationsFail) {
		return nil, false
	}
	return o.PolicyViolationsFail, true
}

// HasPolicyViolationsFail returns a boolean if a field has been set.
func (o *DependencyMetrics) HasPolicyViolationsFail() bool {
	if o != nil && !IsNil(o.PolicyViolationsFail) {
		return true
	}

	return false
}

// SetPolicyViolationsFail gets a reference to the given int32 and assigns it to the PolicyViolationsFail field.
func (o *DependencyMetrics) SetPolicyViolationsFail(v int32) {
	o.PolicyViolationsFail = &v
}

// GetPolicyViolationsWarn returns the PolicyViolationsWarn field value if set, zero value otherwise.
func (o *DependencyMetrics) GetPolicyViolationsWarn() int32 {
	if o == nil || IsNil(o.PolicyViolationsWarn) {
		var ret int32
		return ret
	}
	return *o.PolicyViolationsWarn
}

// GetPolicyViolationsWarnOk returns a tuple with the PolicyViolationsWarn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetPolicyViolationsWarnOk() (*int32, bool) {
	if o == nil || IsNil(o.PolicyViolationsWarn) {
		return nil, false
	}
	return o.PolicyViolationsWarn, true
}

// HasPolicyViolationsWarn returns a boolean if a field has been set.
func (o *DependencyMetrics) HasPolicyViolationsWarn() bool {
	if o != nil && !IsNil(o.PolicyViolationsWarn) {
		return true
	}

	return false
}

// SetPolicyViolationsWarn gets a reference to the given int32 and assigns it to the PolicyViolationsWarn field.
func (o *DependencyMetrics) SetPolicyViolationsWarn(v int32) {
	o.PolicyViolationsWarn = &v
}

// GetPolicyViolationsInfo returns the PolicyViolationsInfo field value if set, zero value otherwise.
func (o *DependencyMetrics) GetPolicyViolationsInfo() int32 {
	if o == nil || IsNil(o.PolicyViolationsInfo) {
		var ret int32
		return ret
	}
	return *o.PolicyViolationsInfo
}

// GetPolicyViolationsInfoOk returns a tuple with the PolicyViolationsInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetPolicyViolationsInfoOk() (*int32, bool) {
	if o == nil || IsNil(o.PolicyViolationsInfo) {
		return nil, false
	}
	return o.PolicyViolationsInfo, true
}

// HasPolicyViolationsInfo returns a boolean if a field has been set.
func (o *DependencyMetrics) HasPolicyViolationsInfo() bool {
	if o != nil && !IsNil(o.PolicyViolationsInfo) {
		return true
	}

	return false
}

// SetPolicyViolationsInfo gets a reference to the given int32 and assigns it to the PolicyViolationsInfo field.
func (o *DependencyMetrics) SetPolicyViolationsInfo(v int32) {
	o.PolicyViolationsInfo = &v
}

// GetPolicyViolationsTotal returns the PolicyViolationsTotal field value if set, zero value otherwise.
func (o *DependencyMetrics) GetPolicyViolationsTotal() int32 {
	if o == nil || IsNil(o.PolicyViolationsTotal) {
		var ret int32
		return ret
	}
	return *o.PolicyViolationsTotal
}

// GetPolicyViolationsTotalOk returns a tuple with the PolicyViolationsTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetPolicyViolationsTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.PolicyViolationsTotal) {
		return nil, false
	}
	return o.PolicyViolationsTotal, true
}

// HasPolicyViolationsTotal returns a boolean if a field has been set.
func (o *DependencyMetrics) HasPolicyViolationsTotal() bool {
	if o != nil && !IsNil(o.PolicyViolationsTotal) {
		return true
	}

	return false
}

// SetPolicyViolationsTotal gets a reference to the given int32 and assigns it to the PolicyViolationsTotal field.
func (o *DependencyMetrics) SetPolicyViolationsTotal(v int32) {
	o.PolicyViolationsTotal = &v
}

// GetPolicyViolationsAudited returns the PolicyViolationsAudited field value if set, zero value otherwise.
func (o *DependencyMetrics) GetPolicyViolationsAudited() int32 {
	if o == nil || IsNil(o.PolicyViolationsAudited) {
		var ret int32
		return ret
	}
	return *o.PolicyViolationsAudited
}

// GetPolicyViolationsAuditedOk returns a tuple with the PolicyViolationsAudited field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetPolicyViolationsAuditedOk() (*int32, bool) {
	if o == nil || IsNil(o.PolicyViolationsAudited) {
		return nil, false
	}
	return o.PolicyViolationsAudited, true
}

// HasPolicyViolationsAudited returns a boolean if a field has been set.
func (o *DependencyMetrics) HasPolicyViolationsAudited() bool {
	if o != nil && !IsNil(o.PolicyViolationsAudited) {
		return true
	}

	return false
}

// SetPolicyViolationsAudited gets a reference to the given int32 and assigns it to the PolicyViolationsAudited field.
func (o *DependencyMetrics) SetPolicyViolationsAudited(v int32) {
	o.PolicyViolationsAudited = &v
}

// GetPolicyViolationsUnaudited returns the PolicyViolationsUnaudited field value if set, zero value otherwise.
func (o *DependencyMetrics) GetPolicyViolationsUnaudited() int32 {
	if o == nil || IsNil(o.PolicyViolationsUnaudited) {
		var ret int32
		return ret
	}
	return *o.PolicyViolationsUnaudited
}

// GetPolicyViolationsUnauditedOk returns a tuple with the PolicyViolationsUnaudited field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetPolicyViolationsUnauditedOk() (*int32, bool) {
	if o == nil || IsNil(o.PolicyViolationsUnaudited) {
		return nil, false
	}
	return o.PolicyViolationsUnaudited, true
}

// HasPolicyViolationsUnaudited returns a boolean if a field has been set.
func (o *DependencyMetrics) HasPolicyViolationsUnaudited() bool {
	if o != nil && !IsNil(o.PolicyViolationsUnaudited) {
		return true
	}

	return false
}

// SetPolicyViolationsUnaudited gets a reference to the given int32 and assigns it to the PolicyViolationsUnaudited field.
func (o *DependencyMetrics) SetPolicyViolationsUnaudited(v int32) {
	o.PolicyViolationsUnaudited = &v
}

// GetPolicyViolationsSecurityTotal returns the PolicyViolationsSecurityTotal field value if set, zero value otherwise.
func (o *DependencyMetrics) GetPolicyViolationsSecurityTotal() int32 {
	if o == nil || IsNil(o.PolicyViolationsSecurityTotal) {
		var ret int32
		return ret
	}
	return *o.PolicyViolationsSecurityTotal
}

// GetPolicyViolationsSecurityTotalOk returns a tuple with the PolicyViolationsSecurityTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetPolicyViolationsSecurityTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.PolicyViolationsSecurityTotal) {
		return nil, false
	}
	return o.PolicyViolationsSecurityTotal, true
}

// HasPolicyViolationsSecurityTotal returns a boolean if a field has been set.
func (o *DependencyMetrics) HasPolicyViolationsSecurityTotal() bool {
	if o != nil && !IsNil(o.PolicyViolationsSecurityTotal) {
		return true
	}

	return false
}

// SetPolicyViolationsSecurityTotal gets a reference to the given int32 and assigns it to the PolicyViolationsSecurityTotal field.
func (o *DependencyMetrics) SetPolicyViolationsSecurityTotal(v int32) {
	o.PolicyViolationsSecurityTotal = &v
}

// GetPolicyViolationsSecurityAudited returns the PolicyViolationsSecurityAudited field value if set, zero value otherwise.
func (o *DependencyMetrics) GetPolicyViolationsSecurityAudited() int32 {
	if o == nil || IsNil(o.PolicyViolationsSecurityAudited) {
		var ret int32
		return ret
	}
	return *o.PolicyViolationsSecurityAudited
}

// GetPolicyViolationsSecurityAuditedOk returns a tuple with the PolicyViolationsSecurityAudited field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetPolicyViolationsSecurityAuditedOk() (*int32, bool) {
	if o == nil || IsNil(o.PolicyViolationsSecurityAudited) {
		return nil, false
	}
	return o.PolicyViolationsSecurityAudited, true
}

// HasPolicyViolationsSecurityAudited returns a boolean if a field has been set.
func (o *DependencyMetrics) HasPolicyViolationsSecurityAudited() bool {
	if o != nil && !IsNil(o.PolicyViolationsSecurityAudited) {
		return true
	}

	return false
}

// SetPolicyViolationsSecurityAudited gets a reference to the given int32 and assigns it to the PolicyViolationsSecurityAudited field.
func (o *DependencyMetrics) SetPolicyViolationsSecurityAudited(v int32) {
	o.PolicyViolationsSecurityAudited = &v
}

// GetPolicyViolationsSecurityUnaudited returns the PolicyViolationsSecurityUnaudited field value if set, zero value otherwise.
func (o *DependencyMetrics) GetPolicyViolationsSecurityUnaudited() int32 {
	if o == nil || IsNil(o.PolicyViolationsSecurityUnaudited) {
		var ret int32
		return ret
	}
	return *o.PolicyViolationsSecurityUnaudited
}

// GetPolicyViolationsSecurityUnauditedOk returns a tuple with the PolicyViolationsSecurityUnaudited field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetPolicyViolationsSecurityUnauditedOk() (*int32, bool) {
	if o == nil || IsNil(o.PolicyViolationsSecurityUnaudited) {
		return nil, false
	}
	return o.PolicyViolationsSecurityUnaudited, true
}

// HasPolicyViolationsSecurityUnaudited returns a boolean if a field has been set.
func (o *DependencyMetrics) HasPolicyViolationsSecurityUnaudited() bool {
	if o != nil && !IsNil(o.PolicyViolationsSecurityUnaudited) {
		return true
	}

	return false
}

// SetPolicyViolationsSecurityUnaudited gets a reference to the given int32 and assigns it to the PolicyViolationsSecurityUnaudited field.
func (o *DependencyMetrics) SetPolicyViolationsSecurityUnaudited(v int32) {
	o.PolicyViolationsSecurityUnaudited = &v
}

// GetPolicyViolationsLicenseTotal returns the PolicyViolationsLicenseTotal field value if set, zero value otherwise.
func (o *DependencyMetrics) GetPolicyViolationsLicenseTotal() int32 {
	if o == nil || IsNil(o.PolicyViolationsLicenseTotal) {
		var ret int32
		return ret
	}
	return *o.PolicyViolationsLicenseTotal
}

// GetPolicyViolationsLicenseTotalOk returns a tuple with the PolicyViolationsLicenseTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetPolicyViolationsLicenseTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.PolicyViolationsLicenseTotal) {
		return nil, false
	}
	return o.PolicyViolationsLicenseTotal, true
}

// HasPolicyViolationsLicenseTotal returns a boolean if a field has been set.
func (o *DependencyMetrics) HasPolicyViolationsLicenseTotal() bool {
	if o != nil && !IsNil(o.PolicyViolationsLicenseTotal) {
		return true
	}

	return false
}

// SetPolicyViolationsLicenseTotal gets a reference to the given int32 and assigns it to the PolicyViolationsLicenseTotal field.
func (o *DependencyMetrics) SetPolicyViolationsLicenseTotal(v int32) {
	o.PolicyViolationsLicenseTotal = &v
}

// GetPolicyViolationsLicenseAudited returns the PolicyViolationsLicenseAudited field value if set, zero value otherwise.
func (o *DependencyMetrics) GetPolicyViolationsLicenseAudited() int32 {
	if o == nil || IsNil(o.PolicyViolationsLicenseAudited) {
		var ret int32
		return ret
	}
	return *o.PolicyViolationsLicenseAudited
}

// GetPolicyViolationsLicenseAuditedOk returns a tuple with the PolicyViolationsLicenseAudited field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetPolicyViolationsLicenseAuditedOk() (*int32, bool) {
	if o == nil || IsNil(o.PolicyViolationsLicenseAudited) {
		return nil, false
	}
	return o.PolicyViolationsLicenseAudited, true
}

// HasPolicyViolationsLicenseAudited returns a boolean if a field has been set.
func (o *DependencyMetrics) HasPolicyViolationsLicenseAudited() bool {
	if o != nil && !IsNil(o.PolicyViolationsLicenseAudited) {
		return true
	}

	return false
}

// SetPolicyViolationsLicenseAudited gets a reference to the given int32 and assigns it to the PolicyViolationsLicenseAudited field.
func (o *DependencyMetrics) SetPolicyViolationsLicenseAudited(v int32) {
	o.PolicyViolationsLicenseAudited = &v
}

// GetPolicyViolationsLicenseUnaudited returns the PolicyViolationsLicenseUnaudited field value if set, zero value otherwise.
func (o *DependencyMetrics) GetPolicyViolationsLicenseUnaudited() int32 {
	if o == nil || IsNil(o.PolicyViolationsLicenseUnaudited) {
		var ret int32
		return ret
	}
	return *o.PolicyViolationsLicenseUnaudited
}

// GetPolicyViolationsLicenseUnauditedOk returns a tuple with the PolicyViolationsLicenseUnaudited field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetPolicyViolationsLicenseUnauditedOk() (*int32, bool) {
	if o == nil || IsNil(o.PolicyViolationsLicenseUnaudited) {
		return nil, false
	}
	return o.PolicyViolationsLicenseUnaudited, true
}

// HasPolicyViolationsLicenseUnaudited returns a boolean if a field has been set.
func (o *DependencyMetrics) HasPolicyViolationsLicenseUnaudited() bool {
	if o != nil && !IsNil(o.PolicyViolationsLicenseUnaudited) {
		return true
	}

	return false
}

// SetPolicyViolationsLicenseUnaudited gets a reference to the given int32 and assigns it to the PolicyViolationsLicenseUnaudited field.
func (o *DependencyMetrics) SetPolicyViolationsLicenseUnaudited(v int32) {
	o.PolicyViolationsLicenseUnaudited = &v
}

// GetPolicyViolationsOperationalTotal returns the PolicyViolationsOperationalTotal field value if set, zero value otherwise.
func (o *DependencyMetrics) GetPolicyViolationsOperationalTotal() int32 {
	if o == nil || IsNil(o.PolicyViolationsOperationalTotal) {
		var ret int32
		return ret
	}
	return *o.PolicyViolationsOperationalTotal
}

// GetPolicyViolationsOperationalTotalOk returns a tuple with the PolicyViolationsOperationalTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetPolicyViolationsOperationalTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.PolicyViolationsOperationalTotal) {
		return nil, false
	}
	return o.PolicyViolationsOperationalTotal, true
}

// HasPolicyViolationsOperationalTotal returns a boolean if a field has been set.
func (o *DependencyMetrics) HasPolicyViolationsOperationalTotal() bool {
	if o != nil && !IsNil(o.PolicyViolationsOperationalTotal) {
		return true
	}

	return false
}

// SetPolicyViolationsOperationalTotal gets a reference to the given int32 and assigns it to the PolicyViolationsOperationalTotal field.
func (o *DependencyMetrics) SetPolicyViolationsOperationalTotal(v int32) {
	o.PolicyViolationsOperationalTotal = &v
}

// GetPolicyViolationsOperationalAudited returns the PolicyViolationsOperationalAudited field value if set, zero value otherwise.
func (o *DependencyMetrics) GetPolicyViolationsOperationalAudited() int32 {
	if o == nil || IsNil(o.PolicyViolationsOperationalAudited) {
		var ret int32
		return ret
	}
	return *o.PolicyViolationsOperationalAudited
}

// GetPolicyViolationsOperationalAuditedOk returns a tuple with the PolicyViolationsOperationalAudited field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetPolicyViolationsOperationalAuditedOk() (*int32, bool) {
	if o == nil || IsNil(o.PolicyViolationsOperationalAudited) {
		return nil, false
	}
	return o.PolicyViolationsOperationalAudited, true
}

// HasPolicyViolationsOperationalAudited returns a boolean if a field has been set.
func (o *DependencyMetrics) HasPolicyViolationsOperationalAudited() bool {
	if o != nil && !IsNil(o.PolicyViolationsOperationalAudited) {
		return true
	}

	return false
}

// SetPolicyViolationsOperationalAudited gets a reference to the given int32 and assigns it to the PolicyViolationsOperationalAudited field.
func (o *DependencyMetrics) SetPolicyViolationsOperationalAudited(v int32) {
	o.PolicyViolationsOperationalAudited = &v
}

// GetPolicyViolationsOperationalUnaudited returns the PolicyViolationsOperationalUnaudited field value if set, zero value otherwise.
func (o *DependencyMetrics) GetPolicyViolationsOperationalUnaudited() int32 {
	if o == nil || IsNil(o.PolicyViolationsOperationalUnaudited) {
		var ret int32
		return ret
	}
	return *o.PolicyViolationsOperationalUnaudited
}

// GetPolicyViolationsOperationalUnauditedOk returns a tuple with the PolicyViolationsOperationalUnaudited field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetPolicyViolationsOperationalUnauditedOk() (*int32, bool) {
	if o == nil || IsNil(o.PolicyViolationsOperationalUnaudited) {
		return nil, false
	}
	return o.PolicyViolationsOperationalUnaudited, true
}

// HasPolicyViolationsOperationalUnaudited returns a boolean if a field has been set.
func (o *DependencyMetrics) HasPolicyViolationsOperationalUnaudited() bool {
	if o != nil && !IsNil(o.PolicyViolationsOperationalUnaudited) {
		return true
	}

	return false
}

// SetPolicyViolationsOperationalUnaudited gets a reference to the given int32 and assigns it to the PolicyViolationsOperationalUnaudited field.
func (o *DependencyMetrics) SetPolicyViolationsOperationalUnaudited(v int32) {
	o.PolicyViolationsOperationalUnaudited = &v
}

// GetFirstOccurrence returns the FirstOccurrence field value
func (o *DependencyMetrics) GetFirstOccurrence() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.FirstOccurrence
}

// GetFirstOccurrenceOk returns a tuple with the FirstOccurrence field value
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetFirstOccurrenceOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstOccurrence, true
}

// SetFirstOccurrence sets field value
func (o *DependencyMetrics) SetFirstOccurrence(v int64) {
	o.FirstOccurrence = v
}

// GetLastOccurrence returns the LastOccurrence field value
func (o *DependencyMetrics) GetLastOccurrence() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LastOccurrence
}

// GetLastOccurrenceOk returns a tuple with the LastOccurrence field value
// and a boolean to check if the value has been set.
func (o *DependencyMetrics) GetLastOccurrenceOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastOccurrence, true
}

// SetLastOccurrence sets field value
func (o *DependencyMetrics) SetLastOccurrence(v int64) {
	o.LastOccurrence = v
}

func (o DependencyMetrics) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DependencyMetrics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["critical"] = o.Critical
	toSerialize["high"] = o.High
	toSerialize["medium"] = o.Medium
	toSerialize["low"] = o.Low
	if !IsNil(o.Unassigned) {
		toSerialize["unassigned"] = o.Unassigned
	}
	if !IsNil(o.Vulnerabilities) {
		toSerialize["vulnerabilities"] = o.Vulnerabilities
	}
	if !IsNil(o.Suppressed) {
		toSerialize["suppressed"] = o.Suppressed
	}
	if !IsNil(o.FindingsTotal) {
		toSerialize["findingsTotal"] = o.FindingsTotal
	}
	if !IsNil(o.FindingsAudited) {
		toSerialize["findingsAudited"] = o.FindingsAudited
	}
	if !IsNil(o.FindingsUnaudited) {
		toSerialize["findingsUnaudited"] = o.FindingsUnaudited
	}
	if !IsNil(o.InheritedRiskScore) {
		toSerialize["inheritedRiskScore"] = o.InheritedRiskScore
	}
	if !IsNil(o.PolicyViolationsFail) {
		toSerialize["policyViolationsFail"] = o.PolicyViolationsFail
	}
	if !IsNil(o.PolicyViolationsWarn) {
		toSerialize["policyViolationsWarn"] = o.PolicyViolationsWarn
	}
	if !IsNil(o.PolicyViolationsInfo) {
		toSerialize["policyViolationsInfo"] = o.PolicyViolationsInfo
	}
	if !IsNil(o.PolicyViolationsTotal) {
		toSerialize["policyViolationsTotal"] = o.PolicyViolationsTotal
	}
	if !IsNil(o.PolicyViolationsAudited) {
		toSerialize["policyViolationsAudited"] = o.PolicyViolationsAudited
	}
	if !IsNil(o.PolicyViolationsUnaudited) {
		toSerialize["policyViolationsUnaudited"] = o.PolicyViolationsUnaudited
	}
	if !IsNil(o.PolicyViolationsSecurityTotal) {
		toSerialize["policyViolationsSecurityTotal"] = o.PolicyViolationsSecurityTotal
	}
	if !IsNil(o.PolicyViolationsSecurityAudited) {
		toSerialize["policyViolationsSecurityAudited"] = o.PolicyViolationsSecurityAudited
	}
	if !IsNil(o.PolicyViolationsSecurityUnaudited) {
		toSerialize["policyViolationsSecurityUnaudited"] = o.PolicyViolationsSecurityUnaudited
	}
	if !IsNil(o.PolicyViolationsLicenseTotal) {
		toSerialize["policyViolationsLicenseTotal"] = o.PolicyViolationsLicenseTotal
	}
	if !IsNil(o.PolicyViolationsLicenseAudited) {
		toSerialize["policyViolationsLicenseAudited"] = o.PolicyViolationsLicenseAudited
	}
	if !IsNil(o.PolicyViolationsLicenseUnaudited) {
		toSerialize["policyViolationsLicenseUnaudited"] = o.PolicyViolationsLicenseUnaudited
	}
	if !IsNil(o.PolicyViolationsOperationalTotal) {
		toSerialize["policyViolationsOperationalTotal"] = o.PolicyViolationsOperationalTotal
	}
	if !IsNil(o.PolicyViolationsOperationalAudited) {
		toSerialize["policyViolationsOperationalAudited"] = o.PolicyViolationsOperationalAudited
	}
	if !IsNil(o.PolicyViolationsOperationalUnaudited) {
		toSerialize["policyViolationsOperationalUnaudited"] = o.PolicyViolationsOperationalUnaudited
	}
	toSerialize["firstOccurrence"] = o.FirstOccurrence
	toSerialize["lastOccurrence"] = o.LastOccurrence
	return toSerialize, nil
}

func (o *DependencyMetrics) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"critical",
		"high",
		"medium",
		"low",
		"firstOccurrence",
		"lastOccurrence",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDependencyMetrics := _DependencyMetrics{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDependencyMetrics)

	if err != nil {
		return err
	}

	*o = DependencyMetrics(varDependencyMetrics)

	return err
}

type NullableDependencyMetrics struct {
	value *DependencyMetrics
	isSet bool
}

func (v NullableDependencyMetrics) Get() *DependencyMetrics {
	return v.value
}

func (v *NullableDependencyMetrics) Set(val *DependencyMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableDependencyMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableDependencyMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDependencyMetrics(val *DependencyMetrics) *NullableDependencyMetrics {
	return &NullableDependencyMetrics{value: val, isSet: true}
}

func (v NullableDependencyMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDependencyMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


