/*
OWASP Dependency-Track

REST API of OWASP Dependency-Track

API version: 4.13.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TagOperationProblemDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagOperationProblemDetails{}

// TagOperationProblemDetails struct for TagOperationProblemDetails
type TagOperationProblemDetails struct {
	// A URI reference that identifies the problem type
	Type *string `json:"type,omitempty"`
	// HTTP status code generated by the origin server for this occurrence of the problem
	Status int32 `json:"status"`
	// Short, human-readable summary of the problem type
	Title string `json:"title"`
	// Human-readable explanation specific to this occurrence of the problem
	Detail string `json:"detail"`
	// Reference URI that identifies the specific occurrence of the problem
	Instance *string `json:"instance,omitempty"`
	// Errors encountered during the operation, grouped by tag name
	Errors *map[string]string `json:"errors,omitempty"`
}

type _TagOperationProblemDetails TagOperationProblemDetails

// NewTagOperationProblemDetails instantiates a new TagOperationProblemDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagOperationProblemDetails(status int32, title string, detail string) *TagOperationProblemDetails {
	this := TagOperationProblemDetails{}
	this.Status = status
	this.Title = title
	this.Detail = detail
	return &this
}

// NewTagOperationProblemDetailsWithDefaults instantiates a new TagOperationProblemDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagOperationProblemDetailsWithDefaults() *TagOperationProblemDetails {
	this := TagOperationProblemDetails{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TagOperationProblemDetails) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagOperationProblemDetails) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TagOperationProblemDetails) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TagOperationProblemDetails) SetType(v string) {
	o.Type = &v
}

// GetStatus returns the Status field value
func (o *TagOperationProblemDetails) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TagOperationProblemDetails) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TagOperationProblemDetails) SetStatus(v int32) {
	o.Status = v
}

// GetTitle returns the Title field value
func (o *TagOperationProblemDetails) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *TagOperationProblemDetails) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *TagOperationProblemDetails) SetTitle(v string) {
	o.Title = v
}

// GetDetail returns the Detail field value
func (o *TagOperationProblemDetails) GetDetail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Detail
}

// GetDetailOk returns a tuple with the Detail field value
// and a boolean to check if the value has been set.
func (o *TagOperationProblemDetails) GetDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Detail, true
}

// SetDetail sets field value
func (o *TagOperationProblemDetails) SetDetail(v string) {
	o.Detail = v
}

// GetInstance returns the Instance field value if set, zero value otherwise.
func (o *TagOperationProblemDetails) GetInstance() string {
	if o == nil || IsNil(o.Instance) {
		var ret string
		return ret
	}
	return *o.Instance
}

// GetInstanceOk returns a tuple with the Instance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagOperationProblemDetails) GetInstanceOk() (*string, bool) {
	if o == nil || IsNil(o.Instance) {
		return nil, false
	}
	return o.Instance, true
}

// HasInstance returns a boolean if a field has been set.
func (o *TagOperationProblemDetails) HasInstance() bool {
	if o != nil && !IsNil(o.Instance) {
		return true
	}

	return false
}

// SetInstance gets a reference to the given string and assigns it to the Instance field.
func (o *TagOperationProblemDetails) SetInstance(v string) {
	o.Instance = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *TagOperationProblemDetails) GetErrors() map[string]string {
	if o == nil || IsNil(o.Errors) {
		var ret map[string]string
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagOperationProblemDetails) GetErrorsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *TagOperationProblemDetails) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given map[string]string and assigns it to the Errors field.
func (o *TagOperationProblemDetails) SetErrors(v map[string]string) {
	o.Errors = &v
}

func (o TagOperationProblemDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagOperationProblemDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	toSerialize["status"] = o.Status
	toSerialize["title"] = o.Title
	toSerialize["detail"] = o.Detail
	if !IsNil(o.Instance) {
		toSerialize["instance"] = o.Instance
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

func (o *TagOperationProblemDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"title",
		"detail",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTagOperationProblemDetails := _TagOperationProblemDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTagOperationProblemDetails)

	if err != nil {
		return err
	}

	*o = TagOperationProblemDetails(varTagOperationProblemDetails)

	return err
}

type NullableTagOperationProblemDetails struct {
	value *TagOperationProblemDetails
	isSet bool
}

func (v NullableTagOperationProblemDetails) Get() *TagOperationProblemDetails {
	return v.value
}

func (v *NullableTagOperationProblemDetails) Set(val *TagOperationProblemDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableTagOperationProblemDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableTagOperationProblemDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagOperationProblemDetails(val *TagOperationProblemDetails) *NullableTagOperationProblemDetails {
	return &NullableTagOperationProblemDetails{value: val, isSet: true}
}

func (v NullableTagOperationProblemDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagOperationProblemDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


