apiVersion: v1
kind: Service
metadata:
  name: {{ include "dependencytrack-backend.name" . }}
  labels:
    {{- include "dependencytrack-backend.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      name: http
  clusterIP: None
  selector:
    {{- include "dependencytrack-backend.selectorLabels" . | nindent 4 }}