apiVersion: v1
kind: Service
metadata:
  name: {{ include "dependencytrack-backend.name" . }}
  labels:
    {{- include "dependencytrack-backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dependencytrack-backend.selectorLabels" . | nindent 4 }}
