apiVersion: networking.gke.io/v1alpha3
kind: FQDNNetworkPolicy
metadata:
  name: {{ .Release.Name }}-fqdn
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    to:
    - fqdns:
      - nvd.nist.gov
      - epss.cyentia.com
      - osv-vulnerabilities.storage.googleapis.com
      - private.googleapis.com
  - ports:
    - port: 80
      protocol: TCP
    to:
    - fqdns:
      - metadata.google.internal
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  policyTypes:
  - Egress
