apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/instance: {{ include "dependencytrack-backend.name" . }}
    app.kubernetes.io/name: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  egress:
    - to:
        - ipBlock:
            cidr: {{ .Values.backend.postgresql.ip }}/32
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}-bootstrap
              app.kubernetes.io/name: {{ .Release.Name }}
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: picante
              app.kubernetes.io/name: picante
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ include "dependencytrack-frontend.name" . }}
              app.kubernetes.io/name: {{ .Release.Name }}
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "dependencytrack-backend.name" . }}
      app.kubernetes.io/name: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-bootstrap
    app.kubernetes.io/name: {{ .Release.Name }}
  name: {{ .Release.Name }}-bootstrap
spec:
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ include "dependencytrack-backend.name" . }}
              app.kubernetes.io/name: {{ .Release.Name }}
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}-bootstrap
      app.kubernetes.io/name: {{ .Release.Name }}
  policyTypes:
    - Egress
---
{{- if .Capabilities.APIVersions.Has "networking.gke.io/v1" }}
apiVersion: networking.gke.io/v1alpha3
kind: FQDNNetworkPolicy
metadata:
  name: {{ include "dependencytrack-backend.name" . }}-fqdn
spec:
  egress:
    - ports:
        - port: 443
          protocol: TCP
      to:
        - fqdns:
            - nvd.nist.gov
            - epss.cyentia.com
            - osv-vulnerabilities.storage.googleapis.com
    - ports:
        - port: 80
          protocol: TCP
      to:
        - fqdns:
            - metadata.google.internal
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "dependencytrack-backend.name" . }}
      app.kubernetes.io/name: {{ .Release.Name }}
  policyTypes:
    - Egress
{{- end }}