apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/instance: {{ include "dependencytrack-backend.name" . }}-backend
    app.kubernetes.io/name: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  egress:
    - to:
        - ipBlock:
            cidr: {{ .Values.backend.postgresql.ip }}/32
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: nais-system
          podSelector:
            matchLabels:
              app: picante
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "dependencytrack-backend.name" . }}-backend
      app.kubernetes.io/name: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
---
{{- if .Capabilities.APIVersions.Has "networking.gke.io/v1" }}
apiVersion: networking.gke.io/v1alpha3
kind: FQDNNetworkPolicy
metadata:
  name: {{ include "dependencytrack-backend.name" . }}-fqdn
spec:
  egress:
    - ports:
        - port: 443
          protocol: TCP
      to:
        - fqdns:
            - nvd.nist.gov
            - epss.cyentia.com
            - osv-vulnerabilities.storage.googleapis.com
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "dependencytrack-backend.name" . }}-backend
      app.kubernetes.io/name: {{ .Release.Name }}
  policyTypes:
    - Egress
{{- end }}