apiVersion: networking.gke.io/v1alpha3
kind: FQDNNetworkPolicy
metadata:
  name: {{ .Release.Name }}-fqdn
spec:
  egress:
    - ports:
        - port: 443
          protocol: TCP
      to:
        - fqdns:
            - nvd.nist.gov
            - epss.cyentia.com
            - osv-vulnerabilities.storage.googleapis.com
            - private.googleapis.com
            - repo.clojars.org
            - repository.jboss.org
            - packages.atlassian.com
            - repo1.maven.org
            - proxy.golang.org
            - pypi.org
            - packages.atlassian.com
            - repo.clojars.org
            - ossindex.sonatype.org
            - registry.npmjs.org
  {{- if .Values.backend.fqdn.google.internal }}
    - ports:
        - port: 80
          protocol: TCP
      to:
        - fqdns:
            - metadata.google.internal
    {{- end }}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  policyTypes:
    - Egress
