apiVersion: v1
kind: Service
metadata:
  name: {{ include "dependencytrack-frontend.name" . }}
  labels:
    {{- include "dependencytrack-frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 81
      targetPort: http-swag
      protocol: TCP
      name: http-swag
  selector:
    {{- include "dependencytrack-frontend.selectorLabels" . | nindent 4 }}
