apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
spec:
  egress:
    - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  policyTypes:
    - Egress