apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
spec:
  egress:
    - to:
        - namespaceSelector: { }
          podSelector:
            matchLabels:
              k8s-app: kube-dns
        - namespaceSelector: { }
          podSelector:
            matchLabels:
              k8s-app: node-local-dns
    - to:
        - ipBlock:
            cidr: {{ .Values.backend.postgresql.ip }}/32
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Release.Name }}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  policyTypes:
    - Egress