kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "dependencytrack-backend.name" . }}
  labels:
{{ include "dependencytrack-backend.labels" . | indent 4 }}
spec:
  accessModes:
    - {{ .Values.backend.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size | quote }}
  storageClassName: {{ .Values.backend.persistence.storageClass | quote }}
