{{if .Values.resync.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "resync-job.name" . }}
  labels:
    app: {{ include "resync-job.name" . }}
    {{- include "resync-job.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.resync.schedule | quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        metadata:
          labels:
            app: {{ include "resync-job.name" . }}
            {{- include "resync-job.labels" . | nindent 8 }}
        spec:
          containers:
            - name: {{ include "resync-job.name" . }}
              image: "{{ .Values.resync.image.repository }}/{{ .Values.resync.image.name }}:{{ .Values.resync.image.tag }}"
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
              env:
                - name: LOG_LEVEL
                  value: "{{ .Values.resync.logLevel }}"
                - name: BASE_URL
                  value: "{{ .Values.resync.baseUrl }}"
              envFrom:
                - secretRef:
                    name: {{ include "resync-job.name" . }}
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
  {{- end }}
