{{if .Values.resync.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resync-job.name" . }}-pwd
  labels:
    app: {{ include "resync-job.name" . }}
    {{- include "resync-job.labels" . | nindent 4 }}
type: Opaque
stringData:
  PASSWORD: {{ .Values.resync.password | quote }}
{{- end }}
