{{- if .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dependencytrack.name" . }}
  labels:
    {{- include "dependencytrack-backend.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.backend.serviceAccount.googleServiceAccountEmail }}
    {{- end }}