apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dependencytrack-backend.name" . }}-postgresql
  labels:
    {{- include "dependencytrack-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresql_password: "{{ .Values.backend.postgresql.password }}"
  postgresql_username: "{{ .Values.backend.postgresql.username }}"
