apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dependencytrack-backend.name" . }}-postgresql
  labels:
    {{- include "dependencytrack-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresql_password: "{{ .Values.backend.postgresql.password }}"
  postgresql_username: "{{ .Values.backend.postgresql.username }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-metrics"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: "{{ .Release.Name }}-metrics"
    app.kubernetes.io/name: {{ .Release.Name | quote }}
type: Opaque
stringData:
  PASSWORD: {{ .Values.bootstrap.adminPassword | quote }}
