apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-key
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
type: Opaque
data:
  secret.key: {{ randAlphaNum 32 | quote }}