apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: trivy-server
spec:
  egress:
    - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: trivy
  policyTypes:
    - Egress