apiVersion: v2
name: dependencytrack
sources:
  - https://github.com/nais/dependencytrack/tree/main/charts
description: A Helm chart for Kubernetes
type: application
version: 0.5.2

dependencies:
  - name: trivy
    version: "0.7.0"
    repository: "https://aquasecurity.github.io/helm-charts"