# Default values for dependencytrack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  name: dependencytrack
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images
  tag: yolo

bootstrap:
  logLevel: INFO
  baseUrl: http://dependencytrack-backend:8080
  frontendBaseUrl:
  defaultAdminPassword: admin
  adminPassword: todo
  github:
    advisory_mirroring_token:
  google:
    osv_enabled: true
  nvd:
    api_key:
  users:
    - username: console
      password: todo
  trivy:
    ignore_unfixed: true
    api_token:
    base_url: http://dependencytrack-trivy:4954

backend:
  logLevel: INFO
  image:
    name: apiserver
    repository: dependencytrack
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 4.11.4
  replicaCount: 2
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      memory: 20Gi
      cpu: "4"
  outbound: [ ]
  ingressClassName: nais-ingress
  ingress:
  livenessProbe:
    enabled: true
    path: "/api/version"
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: true
    path: "/"
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3

  cloudProxy:
    repository: gcr.io/cloudsql-docker/gce-proxy
    tag: 1.35.3

  postgresql:
    enabled: true
    password:
    database: dependencytrack
    username:
    host: 127.0.0.1
    port: 5432
    connectionName:
    ip:

  serviceAccount:
    create: true
    googleServiceAccountEmail:

  persistence:
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClass: "standard"
    existingClaim: ""
  env:
    ALPINE_OIDC_ENABLED: true
    ALPINE_OIDC_ISSUER:
    ALPINE_OIDC_CLIENT_ID:
    ALPINE_OIDC_USERNAME_CLAIM: email
    #ALPINE_OIDC_TEAMS_CLAIM: groups
    ALPINE_OIDC_USER_PROVISIONING: true
    # Optional Cross-Origin Resource Sharing (CORS) Headers
    ALPINE_CORS_ENABLED: true
    ALPINE_CORS_ALLOW_ORIGIN:
    ALPINE_CORS_ALLOW_METHODS: GET, POST, PUT, PATCH, DELETE, OPTIONS
    ALPINE_CORS_ALLOW_HEADERS: Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count, *
    ALPINE_CORS_EXPOSE_HEADERS: Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count
    ALPINE_CORS_ALLOW_CREDENTIALS: true
    ALPINE_CORS_MAX_AGE: 3600
    ALPINE_METRICS_ENABLED: true
    LOGGING_CONFIG_PATH: logback-json.xml
    # ALPINE_OIDC_TEAM_SYNCHRONIZATION: true

frontend:
  swagger:
    enabled: false
    path: /swagger
    port: 8181
  image:
    name: frontend
    repository: dependencytrack
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 4.11.4
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      memory: 1Gi
      cpu: "2"
  outbound: [ ]
  ingressClassName: nais-ingress
  ingress:
  env:
    # auth code flow without client_secret using pkce not supported by google.
    # https://stackoverflow.com/questions/60724690/using-google-oidc-with-code-flow-and-pkce
    OIDC_FLOW: implicit
    API_BASE_URL:
    OIDC_ISSUER:
    OIDC_CLIENT_ID:

trivy:
  replicaCount: 2
  image:
    registry: "ghcr.io"
    repository: "aquasecurity/trivy"
    tag: "0.52.2"
  serverToken: "todo"
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
